<?php
namespace Flownode\Switchboard;

/**
 * Test class for SwitchBoard.
 * Generated by PHPUnit on 2012-11-02 at 22:33:49.
 */
class SwitchBoardTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SwitchBoard
     */
    protected $sb;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->sb = SwitchBoard::get();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers SwitchBoard\SwitchBoard::register
     * @todo Implement testRegister().
     */
    public function testRegister()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SwitchBoard\SwitchBoard::get
     * @todo Implement testGet().
     */
    public function testGet()
    {
        //$sb = SwitchBoard::get();

        //$this->assertInstanceOf('SwitchBoard\SwitchBoard', $sb);
    }

    /**
     * @covers SwitchBoard\SwitchBoard::connect
     * @todo Implement testConnect().
     */
    public function testConnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SwitchBoard\SwitchBoard::resolve
     * @todo Implement testResolve().
     */
    public function testResolve()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}