<?php
namespace Flownode\Node;

/**
 * Test class for Node.
 * Generated by PHPUnit on 2012-11-25 at 23:18:38.
 */
class NodeTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Node
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Node;

  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::open
   * @todo Implement testOpen().
   */
  public function testOpen()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::close
   * @todo Implement testClose().
   */
  public function testClose()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::setAttributes
   * @todo Implement testSetAttributes().
   */
  public function testSetAttributes()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::set
   * @todo Implement testSet().
   */
  public function testSet()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::setAttribute
   * @todo Implement testSetAttribute().
   */
  public function testSetAttribute()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::getParent
   * @todo Implement testGetParent().
   */
  public function testGetParent()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::setParent
   * @todo Implement testSetParent().
   */
  public function testSetParent()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::addChild
   * @todo Implement testAddChild().
   */
  public function testAddChild()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::getText
   * @todo Implement testGetText().
   */
  public function testGetText()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::setText
   * @todo Implement testSetText().
   */
  public function testSetText()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::getAttributesString
   * @todo Implement testGetAttributesString().
   */
  public function testGetAttributesString()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::setTemplate
   * @todo Implement testSetTemplate().
   */
  public function testSetTemplate()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::__call
   * @todo Implement test__call().
   */
  public function test__call()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

  /**
   * @covers Flownode\UI\Common\DOM\Node::setTagName
   * @todo Implement testSetTagName().
   */
  public function testSetTagName()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );

  }

}
?>
